### ISSUE TITLE
Cannot open source input file "nanostack/platform/arm_hal_phy.h": No such file or directory 

### ISSUE THREAD

**Issue by g00223903** [ARMmbed/atmel-rf-driver#46] opened 2016-11-02 22:57 UTC
Hello,
When following the example [https://docs.mbed.com/docs/building-an-internet-connected-lighting-system/en/latest/](url) I am getting the error "Cannot open source input file "nanostack/platform/arm_hal_phy.h": No such file or directory ". I am trying to connect the K64F via ethernet but when I try to compile the project it fails.
![err](https://cloud.githubusercontent.com/assets/22446548/19950463/995e799c-a14f-11e6-95af-3fda8a6b280a.png)

Any ideas how to fix this?
Thank you.

**Comment by ciarmcom** [comment] 2016-11-03 00:49
ARM Internal Ref: ONME-2849

**Comment by SeppoTakalo** [comment] 2016-11-03 15:01
Hi @g00223903 
Please see https://github.com/ARMmbed/atmel-rf-driver/issues/41

The example application seems not to be up to date with mbed OS 5.2

**Comment by SeppoTakalo** [comment] 2016-11-24 09:00
Closing this as the problem is the example application being outdated.

**Closed by SeppoTakalo** 2016-11-24 09:00 UTC
Labels: mirrored
