### ISSUE TITLE
Allow other ways of providing the MAC

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/atmel-rf-driver#36] opened 2016-08-12 12:32 UTC
In https://github.com/ARMmbed/atmel-rf-driver/blob/4fb763e3a34c8ad501c111c1e007854349ae18ed/source/driverRFPhy.c#L118
it is required to read the MAC from a very specific chip, that is on the example shields:
```
    if (0 != at24mac_read_eui64(atmel_MAC))
        return -1; //No MAC
```

For other hardware, that does not have the same chip providing the MAC, you therefore require to fork atmel-rf-driver and modify it. The only modification required is to comment/delete the two lines above and set the MAC before calling rf_device_register().

Please allow for an MBED_CONF_* config value to disable this fragment. Then we do not need to fork this repo.

**Comment by markus-becker-tridonic-com** [comment] 2016-08-12 12:33
@MarceloSalazar

**Comment by MarceloSalazar** [comment] 2016-08-12 12:47
@SeppoTakalo @hasnainvirk could you please consider this enhancement?

**Comment by hasnainvirk** [comment] 2016-08-12 13:12
@markus-becker-tridonic-com @MarceloSalazar  Can I then hope that all the users will somehow provide atmel-rf-driver with a valid Unique MAC address ?
The easiest way to kill whole network is by using a same MAC address on a network.

**Comment by markus-becker-tridonic-com** [comment] 2016-08-12 14:08
I don't know about all the users, but our devices will have unique MACs stored in a different way.

The default way of looking up the MAC in the AT24 is fine, it's just that at the moment you are unnecessarily limiting yourself to this. If we disable reading the MAC from AT24, and then not provide a MAC it's our fault, or? You could check against not having set one and bail out if it wasn't, to be super-sure.

**Comment by hasnainvirk** [comment] 2016-08-12 14:29
@MarceloSalazar @markus-becker-tridonic-com 
https://github.com/ARMmbed/atmel-rf-driver/pull/37

**Comment by kjbracey-arm** [comment] 2016-08-12 14:46
Having the board support code call rf_set_mac_address before initialising the driver is indeed the intended functionality, and the way the non-mbed-OS ports of the driver work.

The AT24MAC driver just got bundled to the mbed OS RF driver for convenience, I guess, hard-connecting them together.

I don't know if it's worth connecting the AT24MAC driver up to mbed OS better - doesn't mbed OS have a "get MAC" API that it could be plumbed into? Then it could be fully separated.

Again, that's the way it was intended to work "board_get_mac()" would call "at24_read_mac()", and then the portable startup code would pass that in to "rf_set_mac_address()".

**Comment by ciarmcom** [comment] 2016-08-12 15:49
ARM Internal Ref: ONME-2742

**Comment by hasnainvirk** [comment] 2016-08-16 08:40
https://github.com/ARMmbed/atmel-rf-driver/commit/a4f5b93c69dc7d6dd45a2e415697968b7077b2e7
Fix merged to master.

**Closed by hasnainvirk** 2016-08-16 08:40 UTC
Labels: mirrored
